// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppstoreOutlined: typeof import('@ant-design/icons-vue')['AppstoreOutlined']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    FlexMenuAlpha: typeof import('./components/flexmenus/FlexMenuAlpha.vue')['default']
    HelloWorld: typeof import('./components/test/HelloWorld.vue')['default']
    MenuOutlined: typeof import('@ant-design/icons-vue')['MenuOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/navigations/Sidebar.vue')['default']
  }
}
