// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    CardFlow: typeof import('./views/CardFlow.vue')['default']
    FlexMenu: typeof import('./views/FlexMenu.vue')['default']
    FlexMenuAlpha: typeof import('./components/flexmenus/FlexMenuAlpha.vue')['default']
    HelloWorld: typeof import('./components/test/HelloWorld.vue')['default']
    MainContentBox: typeof import('./views/MainContentBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/navigations/Sidebar.vue')['default']
  }
}
